version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm i @nrwl/nx-linux-x64-gnu && npm install
  build:
    on-failure: ABORT
    commands:
      - npm run build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
artifacts:
  enable-symlinks: yes
  base-directory: 'dist'
  files:
    - '**/*'
