version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - cp -R node_modules/ dist/node_modules
artifacts:
  type: zip
  base-directory: 'dist'
  files:
    - '**/*'
