import { usePersistLogs, useUsers } from '@/lib/compass-api';
import { useDddice } from '@/pages';
import { CharacterContext, diceRollLogger, LogType, useEventLog } from '@/stores';
import type { DiceResult, DiceRollOpts, IDiceContext, RollResult, SegmentResult } from '@/types';
import { createContext, useContext, useRef, useState } from 'react';
import { formatSegmentResult, rollDiceExpression } from '../../utils';

interface DiceStateProps {
  canvasRef?: React.RefObject<HTMLCanvasElement | null>;
}

export const useDiceState = ({ canvasRef }: DiceStateProps): IDiceContext => {
  const [dicePanelOpen, setDicePanelOpen] = useState(false);
  const { logEvent } = useEventLog();
  const { persistLog } = usePersistLogs();
  const { currentUser } = useUsers();

  const characterContext = useContext(CharacterContext);

  const physicalRolls = currentUser?.preferences?.physicalRolls ?? false;
  const [physicalRollModal, setPhysicalRollModal] = useState<{
    notation: string;
    initialValues?: number[];
    rerollMessage?: string;
  } | null>(null);
  const physicalRollResolveRef = useRef<((result: DiceResult) => void) | null>(null);
  const physicalRollRejectRef = useRef<(() => void) | null>(null);

  const [lastResult, setLastResult] = useState<{
    total: number;
    segments: SegmentResult[];
    notation: string;
  } | null>(null);
  const [isRolling, setIsRolling] = useState(false);
  const [dddiceRolling, setDddiceRolling] = useState<boolean>(false);

  const rolling = isRolling || dddiceRolling;

  const dddiceState = useDddice({
    canvasRef,
  });

  const submitPhysicalRollResult = async (result: DiceResult) => {
    setPhysicalRollModal(null);
    physicalRollResolveRef.current?.(result);
    physicalRollResolveRef.current = null;
    physicalRollRejectRef.current = null;
  };

  const dismissPhysicalRollModal = () => {
    setPhysicalRollModal(null);
    setIsRolling(false);
    physicalRollRejectRef.current?.();
    physicalRollResolveRef.current = null;
    physicalRollRejectRef.current = null;
  };

  const rollDice = async (roll: string, opts?: DiceRollOpts) => {
    setLastResult(null);
    const hasRerollMessage =
      opts?.rerollMessage != null && String(opts.rerollMessage).trim() !== '';
    const physicalDice = physicalRolls;
    setIsRolling(true);

    try {
      // 1. If physicalDice, prompt for input; else generate result
      let result: DiceResult;
      if (physicalDice) {
        setPhysicalRollModal({ notation: roll.trim() });
        result = await new Promise<DiceResult>((resolve, reject) => {
          physicalRollResolveRef.current = resolve;
          physicalRollRejectRef.current = reject;
        });
      } else {
        if (opts?.openPanel !== false) {
          setDicePanelOpen(true);
        }
        const { total, segmentResults } = rollDiceExpression(roll);
        result = { total, segments: segmentResults, notation: roll.trim() };
      }

      // 2. If dddice username, trigger and wait for dddice roll
      if (dddiceState.username && !physicalDice) {
        setDddiceRolling(true);
        const diceRollSegments = result.segments.filter((segment) =>
          segment.notation.includes('d'),
        );
        const diceRolls: RollResult[] = diceRollSegments.flatMap((segment) => segment.rolls);
        await dddiceState.rollThreeDDice(diceRolls);
        await new Promise((res) => setTimeout(res, 2000));
        setDddiceRolling(false);
      }

      // 3. If hasRerollMessage, prompt for re-roll input to overwrite result
      if (hasRerollMessage) {
        const initialValues = result.segments.flatMap((s) => s.rolls.map((r) => r.value));
        setPhysicalRollModal({
          notation: roll.trim(),
          initialValues,
          rerollMessage: String(opts!.rerollMessage).trim(),
        });
        result = await new Promise<DiceResult>((resolve, reject) => {
          physicalRollResolveRef.current = resolve;
          physicalRollRejectRef.current = reject;
        });
      }

      // 4. Persist and return
      await diceRollLogger.logRoll(result, {
        source: 'Dice Panel',
      });
      setLastResult(result);
      const breakdown = result.segments.map(formatSegmentResult).join('; ');
      logEvent({
        type: LogType.DICE,
        source: 'Dice Panel',
        message: `${breakdown} → Total: ${result.total}`,
      });

      if (characterContext?.character) {
        const logMessage = `${characterContext.character.name} rolled a ${result.total}`;
        await persistLog({
          logMessages: [[logMessage]],
          context: 'dice_panel',
          scriptId: 'dice-panel',
          autoGenerated: true,
        });
      }

      return result;
    } finally {
      setIsRolling(false);
      setDddiceRolling(false);
    }
  };

  const reset = () => {
    setLastResult(null);
  };

  return {
    dicePanelOpen,
    setDicePanelOpen,
    rollDice,
    lastResult,
    setLastResult,
    isRolling: rolling,
    reset,
    physicalRollModal,
    submitPhysicalRollResult,
    dismissPhysicalRollModal,
    ...dddiceState,
  };
};

export const DiceContext = createContext<IDiceContext>(null!);
export const DiceProvider = DiceContext.Provider;
