/**
 * Centralized script log persistence for QBScript.
 * Persists user log() output and optionally adds auto-generated log entries
 * (e.g. "Script ran") marked with autoGenerated: true.
 */

import type { ScriptLog } from '@quest-bound/types';
import type { ScriptGameLogEntry } from '@/lib/compass-logic/runtime/script-game-log';

/** Minimal DB interface for script log persistence (works in main thread and worker). */
export interface ScriptLogDb {
  scriptLogs: { add: (log: ScriptLog) => Promise<string> };
}

/** Contexts that receive an auto-generated "Script ran" log entry. */
const AUTO_LOG_CONTEXTS = [''];

export interface PersistScriptLogsParams {
  rulesetId: string;
  scriptId: string;
  characterId: string | null;
  /** Used when `gameLogTimeline` is empty or omitted. */
  logMessages?: any[][];
  /** Interleaved `log()` and roll summaries (preferred when present and non-empty). */
  gameLogTimeline?: ScriptGameLogEntry[];
  context: string;
  campaignId?: string | null;
  /** Optional script name for auto-generated entry message. */
  scriptName?: string | null;
  autoGenerated?: boolean;
  /**
   * When several persist calls belong to one script run, pass the same wall time so the game log
   * orders them with `sequence` instead of splitting on clock skew.
   */
  batchTimestamp?: number;
  /** First row's `sequence` for this call (default 0). */
  sequenceStart?: number;
}

/**
 * Persist script log messages to the database and optionally add one auto-generated
 * entry for certain contexts (e.g. load, character_load). Auto-generated entries
 * are marked with autoGenerated: true so the UI can filter or style them.
 */
export async function persistScriptLogs(
  db: ScriptLogDb,
  params: PersistScriptLogsParams,
): Promise<void> {
  const {
    rulesetId,
    scriptId,
    characterId,
    logMessages = [],
    gameLogTimeline,
    context,
    campaignId = null,
    scriptName,
    autoGenerated = false,
    batchTimestamp,
    sequenceStart,
  } = params;

  const now = new Date().toISOString();
  const timestamp = batchTimestamp ?? Date.now();
  const addAutoEntry = AUTO_LOG_CONTEXTS.includes(context);

  const entries: ScriptGameLogEntry[] =
    gameLogTimeline && gameLogTimeline.length > 0
      ? gameLogTimeline
      : logMessages.map((args) => ({ kind: 'log', args }));

  try {
    let seq = sequenceStart ?? 0;
    for (const entry of entries) {
      let argsJson: string;
      let rowAuto: boolean;
      if (entry.kind === 'log') {
        rowAuto = autoGenerated;
        try {
          argsJson = JSON.stringify(entry.args);
        } catch {
          argsJson = JSON.stringify(entry.args.map((a: unknown) => String(a)));
        }
      } else {
        rowAuto = true;
        argsJson = JSON.stringify([entry.message]);
      }
      await db.scriptLogs.add({
        id: crypto.randomUUID(),
        rulesetId,
        campaignId,
        scriptId,
        characterId,
        argsJson,
        timestamp,
        sequence: seq,
        context,
        autoGenerated: rowAuto,
        createdAt: now,
        updatedAt: now,
      } as ScriptLog);
      seq += 1;
    }

    if (addAutoEntry) {
      const label = scriptName ?? scriptId;
      const message =
        context === 'character_load' ? `Character loader ran` : `Script ran: ${label}`;
      await db.scriptLogs.add({
        id: crypto.randomUUID(),
        rulesetId,
        campaignId,
        scriptId,
        characterId,
        argsJson: JSON.stringify([message]),
        timestamp,
        sequence: seq,
        context,
        autoGenerated: true,
        createdAt: now,
        updatedAt: now,
      } as ScriptLog);
    }
  } catch (e) {
    console.warn('[QBScript] Failed to persist script logs:', e);
  }
}

/** Params for persisting a single auto-generated event invocation log. */
export interface PersistEventInvocationLogParams {
  rulesetId: string;
  scriptId: string;
  characterId: string;
  campaignId?: string | null;
  /** Log context, e.g. 'action_event' | 'item_event' | 'campaign_event'. */
  context: string;
  batchTimestamp?: number;
  sequenceStart?: number;
}

/**
 * Persist a single auto-generated event invocation log (e.g. "Alice called Attack on Bob").
 * Message format is built by getEventInvocationLogMessage() so it can be altered in one place.
 */
export async function persistEventInvocationLog(
  db: ScriptLogDb,
  params: PersistEventInvocationLogParams,
  message: string,
): Promise<void> {
  await persistScriptLogs(db, {
    ...params,
    characterId: params.characterId,
    logMessages: [[message]],
    autoGenerated: true,
  });
}
