import type { GridColumn } from '@/components';
import type { Item } from '@/types';

export const itemChartColumns: GridColumn<Item>[] = [
  {
    field: 'controls',
    headerName: '',
    editable: false,
    sortIndex: 0,
    width: 100,
    resizable: false,
  },
  {
    field: 'title',
    headerName: 'Title',
    editable: true,
    filter: true,
    sortIndex: 0,
  },
  {
    field: 'category',
    headerName: 'Category',
    editable: true,
    filter: true,
    width: 150,
    sortIndex: 1,
  },
  {
    field: 'isContainer',
    headerName: 'Container',
    editable: true,
    filter: true,
    sortIndex: 2,
    width: 120,
  },
  {
    field: 'isStorable',
    headerName: 'Storable',
    editable: true,
    filter: true,
    sortIndex: 3,
    width: 120,
  },
  {
    field: 'isEquippable',
    headerName: 'Equippable',
    editable: true,
    filter: true,
    sortIndex: 4,
    width: 120,
  },
  {
    field: 'isConsumable',
    headerName: 'Consumable',
    editable: true,
    filter: true,
    sortIndex: 5,
    width: 120,
  },
  {
    field: 'weight',
    headerName: 'Weight',
    editable: true,
    filter: true,
    sortIndex: 1,
    width: 120,
  },
  {
    field: 'defaultQuantity',
    headerName: 'Default QTY',
    editable: true,
    filter: true,
    sortIndex: 1,
    width: 120,
  },
  {
    field: 'stackSize',
    headerName: 'Stack Size',
    editable: true,
    filter: true,
    sortIndex: 1,
    width: 120,
  },
  {
    field: 'description',
    headerName: 'Description',
    editable: true,
    cellEditor: 'agLargeTextCellEditor',
    cellEditorPopup: true,
    sortIndex: 5,
    flex: 1,
    minWidth: 200,
  },
];
