/**
 * Centralized script log persistence for QBScript.
 * Persists user log() output and optionally adds auto-generated log entries
 * (e.g. "Script ran") marked with autoGenerated: true.
 */

import type { ScriptLog } from '@/types';

/** Minimal DB interface for script log persistence (works in main thread and worker). */
export interface ScriptLogDb {
  scriptLogs: { add: (log: ScriptLog) => Promise<string> };
}

/** Contexts that receive an auto-generated "Script ran" log entry. */
const AUTO_LOG_CONTEXTS = [''];

export interface PersistScriptLogsParams {
  rulesetId: string;
  scriptId: string;
  characterId: string | null;
  logMessages: any[][];
  context: string;
  campaignId?: string | null;
  /** Optional script name for auto-generated entry message. */
  scriptName?: string | null;
  autoGenerated?: boolean;
}

/**
 * Persist script log messages to the database and optionally add one auto-generated
 * entry for certain contexts (e.g. load, character_load). Auto-generated entries
 * are marked with autoGenerated: true so the UI can filter or style them.
 */
export async function persistScriptLogs(
  db: ScriptLogDb,
  params: PersistScriptLogsParams,
): Promise<void> {
  const {
    rulesetId,
    scriptId,
    characterId,
    logMessages,
    context,
    campaignId = null,
    scriptName,
    autoGenerated = false,
  } = params;

  const now = new Date().toISOString();
  const timestamp = Date.now();
  const addAutoEntry = AUTO_LOG_CONTEXTS.includes(context);

  try {
    let seq = 0;
    for (const args of logMessages) {
      let argsJson: string;
      try {
        argsJson = JSON.stringify(args);
      } catch {
        argsJson = JSON.stringify(args.map((a: unknown) => String(a)));
      }
      await db.scriptLogs.add({
        id: crypto.randomUUID(),
        rulesetId,
        campaignId,
        scriptId,
        characterId,
        argsJson,
        timestamp,
        sequence: seq,
        context,
        autoGenerated,
        createdAt: now,
        updatedAt: now,
      } as ScriptLog);
      seq += 1;
    }

    if (addAutoEntry) {
      const label = scriptName ?? scriptId;
      const message =
        context === 'character_load' ? `Character loader ran` : `Script ran: ${label}`;
      await db.scriptLogs.add({
        id: crypto.randomUUID(),
        rulesetId,
        campaignId,
        scriptId,
        characterId,
        argsJson: JSON.stringify([message]),
        timestamp,
        sequence: seq,
        context,
        autoGenerated: true,
        createdAt: now,
        updatedAt: now,
      } as ScriptLog);
    }
  } catch (e) {
    console.warn('[QBScript] Failed to persist script logs:', e);
  }
}

/** Params for persisting a single auto-generated event invocation log. */
export interface PersistEventInvocationLogParams {
  rulesetId: string;
  scriptId: string;
  characterId: string;
  campaignId?: string | null;
  /** Log context, e.g. 'action_event' | 'item_event' | 'campaign_event'. */
  context: string;
}

/**
 * Persist a single auto-generated event invocation log (e.g. "Alice called Attack on Bob").
 * Message format is built by getEventInvocationLogMessage() so it can be altered in one place.
 */
export async function persistEventInvocationLog(
  db: ScriptLogDb,
  params: PersistEventInvocationLogParams,
  message: string,
): Promise<void> {
  await persistScriptLogs(db, {
    ...params,
    characterId: params.characterId,
    logMessages: [[message]],
    autoGenerated: true,
  });
}
